### ISSUE TITLE
no bin target named `snapctr`

### ISSUE THREAD

**Issue by amirkmzh** [faasten/faasten#26]
After installing Rust and trying to build the project with cargo, I've encountered the following errors:

- error: no bin target named `snapctr`
- error: no bin target named `fc_wrapper`
However, binary `firerunner` was built successfully. There is no binary named snapctr or fc_wrapper in snapfaas/bins directory. I would appreciate you helping me solve this problem.

**Comment by alevy** [comment]
Those have been renamed:

`singlevm` and `multivm`, respectively run a single function once with a single request and a bunch of functions as a whole system.

We indeed should update the documentation, quite a bit of the ergonomics are in flux. Sorry! (PRs welcome)
