### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by tan-yue** [faasten/faasten#75]
The syscall `delete` only unlinks an object from its direct parent directory from the specified path. Faasten relies on garbage collection to recycle objects to which there is _no_ path from the well known root directory.

A straightforward and simple way is to _periodically_:
1. starting from the root directory, build a set of in-tree objects;
2. sweep the backing storage and recycle those objects not in the set built from step 1.

Note that reference counting garbage collection does not suit Faasten well. This is because Faasten allows a directory to be
hardlinked multiple times. As a result, there can be cycles, (e.g., alice_photo can link bob_photo and bob_photo can link
alice_photo). An algorithm must detect cycles to decrement objects' reference counters correctly. To detect cycles, _essentially_, 
an algorithm maintains a set of objects (or nodes in graph theory terms) that have been seen.

**Comment by tan-yue** [comment]
From Gongqi:

> For the reference counting garbage collection, can't we do something similar to Weak reference in Rc?
> Given an example of doubly linked list:
> ```rust
> pub struct Node<T> {
>     elem: T,
>     next: Option<Rc<RefCell<Node<T>>>>,
>     prev: Option<Rc<RefCell<Node<T>>>>,
> }
> ```
> for node A <-> node B, A holds the ownership of B and vice versa.
> If drop A, A's ref count decreases to 1 because B still holds A. Then if drop B, B's ref count decrease to 1 because A holds B. This is a ref cycle which introduces memory leak.
> 
> A way to avoid this in Rust is to change the above code to
> ```rust
> pub struct Node<T> {
>     elem: T,
>     next: Option<Rc<RefCell<Node<T>>>>,
>     prev: Option<Weak<RefCell<Node<T>>>>,
> }
> ```
> A weak reference essentially owns the inner value but doesn't increase the (strong) reference count. To access the inner type, a weak ref can call upgrade(&self) -> Option<Rc<T>> to either get the Rc<T> or nothing.
> This is like to have a softlink to the file, and let the developer to handle the failed access.

**Comment by tan-yue** [comment]
Currently the design doesn't have a soft link, i.e., weak reference.

I certainly see that disallowing hard links to a directory and using soft links instead can help the cycle problem. I think, however, the drawback is the dangling problem when the linked directory is moved. It will appear as if the directory is removed. 

I think a dangling soft link is an issue for Faasten because the reason for linking is to express sharing between users, which isn't really why people use soft links in POSIX. That is, when alice shares a directory of photos with bob, the directories should remain shared with bob wherever alice moves the directory. This means we must always update all soft links whenever a directory moves.

**Comment by cherrypiejam** [comment]
I see. What if alice shares a directory with bob and decides not to share it later? Instead of unlinking the directory, should alice remove its content (suppose alice has the write privilege to it)?

**Comment by tan-yue** [comment]
> I see. What if alice shares a directory with bob and decides not to share it later? Instead of unlinking the directory, should alice remove its content (suppose alice has the write privilege to it)?

Right. I think this should be application logic. The application should keep a record of the sharing and unsharing means reading the record and unlinking and also raising the label to remove Bob from the secrecy.

Moreover, Alice always has the unlink permission because in the first place it is Alice creates the link.

**Comment by cherrypiejam** [comment]
Well, I think there are two options if we still want reference counting
1. we don't worry about cycles and have a garbage collector to deal with them
2. (w/o gc) each time we decrement an object's reference count, we do a cycle detection to that object. For example, [link](https://wiki.c2.com/?ReferenceCountingCanHandleCycles). This adds extra overhead each time we decrement an object's reference count. But considering only directory objects reference each other and presumably, unlinking a directory happens rarely, the amortized overhead may be acceptable.

**Comment by tan-yue** [comment]
> 1. we don't worry about cycles and have a garbage collector to deal with them

I actually didn't quite understand this option. Why do we want reference counting then? Isn't reference counting a way of doing garbage collection.

> EDIT: on second thought, the latter option requires you to taint with the highest label to detect cycles (traverse cycles), so having a garbage collector handle cycles may be better.

This is a good point. In addition, cycle detection is needed at linking times as well, not just at unlinking times.

**Comment by cherrypiejam** [comment]
> I actually didn't quite understand this option. Why do we want reference counting then? Isn't reference counting a way of doing garbage collection.
Just a hybrid approach that takes some loads off from running a garbage collector. Writes are usually heavier than reads, so we probably want to avoid a situation where many writes are issued all at once periodically.
